name: Release core-infra

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

jobs:
  build-for-release:
    uses: Stamper-Labs/core-flows/.github/workflows/yarn-node-build.yml@v1.9.0
    with:
      node_version: "22"
      release_mode: 'yes'
    secrets: inherit